name: HeterBaseline_opv2v_camera_v2xvit_prope_ft_full
root_dir: "dataset/OPV2V/train"
validate_dir: "dataset/OPV2V/validate"
test_dir: "dataset/OPV2V/test"

yaml_parser: "load_general_params"
train_params:
  batch_size: 1
  epoches: 40
  eval_freq: 2
  save_freq: 2
  max_cav: 5
  # Fine-tune all parameters from an RPE checkpoint after swapping pos_encoding.
  freeze_bn: true

comm_range: 70
input_source: ["camera", "depth"]
label_type: "camera"
cav_lidar_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]
add_data_extension: ["bev_visibility.png"]

heter:
  assignment_path: "opencood/logs/heter_modality_assign/opv2v_4modality.json"
  ego_modality: "m2"
  mapping_dict:
    m1: m2
    m2: m2
    m3: m2
    m4: m2
  modality_setting:
    m2:
      sensor_type: "camera"
      core_method: "lift_splat_shoot"
      grid_conf:
        xbound: [-51.2, 51.2, 0.4]
        ybound: [-51.2, 51.2, 0.4]
        zbound: [-10, 10, 20.0]
        ddiscr: [2, 50, 48]
        mode: "LID"
      data_aug_conf:
        resize_lim: [0.65, 0.7]
        final_dim: [384, 512]
        rot_lim: [-3.6, 3.6]
        H: 600
        W: 800
        rand_flip: false
        bot_pct_lim: [0.0, 0.05]
        cams: ["camera0", "camera1", "camera2", "camera3"]
        Ncams: 4

fusion:
  core_method: "intermediateheter"
  dataset: "opv2v"
  args:
    proj_first: false
    grid_conf: None
    data_aug_conf: None

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: ["x"]
  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [-0.78539816, 0.78539816]
  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [0.95, 1.05]

preprocess:
  core_method: "SpVoxelPreprocessor"
  args:
    voxel_size: [0.4, 0.4, 4]
    max_points_per_voxel: 1
    max_voxel_train: 1
    max_voxel_test: 1
  cav_lidar_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]

postprocess:
  core_method: "VoxelPostprocessor"
  gt_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]
  anchor_args:
    cav_lidar_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]
    l: 3.9
    w: 1.6
    h: 1.56
    r: [0, 90]
    feature_stride: 4
    num: 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.2
  order: "hwl"
  max_num: 150
  nms_thresh: 0.15
  dir_args:
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: [0, 90]

model:
  core_method: "heter_model_baseline"
  args:
    ego_modality: "m2"
    lidar_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]
    m2:
      core_method: "lift_splat_shoot"
      sensor_type: "camera"
      encoder_args:
        anchor_number: 2
        grid_conf:
          xbound: [-51.2, 51.2, 0.4]
          ybound: [-51.2, 51.2, 0.4]
          zbound: [-10, 10, 20.0]
          ddiscr: [2, 50, 48]
          mode: "LID"
        data_aug_conf:
          resize_lim: [0.65, 0.7]
          final_dim: [384, 512]
          rot_lim: [-3.6, 3.6]
          H: 600
          W: 800
          rand_flip: false
          bot_pct_lim: [0.0, 0.05]
          cams: ["camera0", "camera1", "camera2", "camera3"]
          Ncams: 4
        img_downsample: 8
        img_features: 128
        use_depth_gt: false
        depth_supervision: true
        camera_encoder: "EfficientNet"
      camera_mask_args:
        cav_lidar_range: [-51.2, -51.2, -3, 51.2, 51.2, 1]
        grid_conf:
          xbound: [-51.2, 51.2, 0.4]
          ybound: [-51.2, 51.2, 0.4]
          zbound: [-10, 10, 20.0]
          ddiscr: [2, 50, 48]
          mode: "LID"
      backbone_args:
        layer_nums: [3, 5, 8]
        layer_strides: [2, 2, 2]
        num_filters: [64, 128, 256]
        upsample_strides: [1, 2, 4]
        num_upsample_filter: [128, 128, 128]
        inplanes: 128
      shrink_header:
        kernal_size: [3]
        stride: [2]
        padding: [1]
        dim: [256]
        input_dim: 384

    fusion_method: "v2xvit"
    v2xvit:
      transformer:
        encoder:
          num_blocks: 1
          depth: 3
          use_roi_mask: true
          use_RTE: false
          RTE_ratio: 0
          cav_att_config:
            dim: 256
            use_hetero: true
            use_RTE: false
            RTE_ratio: 0
            heads: 8
            dim_head: 32
            dropout: 0.3
          pwindow_att_config:
            dim: 256
            heads: [16, 8, 4]
            dim_head: [16, 32, 64]
            dropout: 0.3
            window_size: [4, 8, 16]
            relative_pos_embedding: true
            fusion_method: "split_attn"
            pos_encoding: "prope"
          feed_forward:
            mlp_dim: 256
            dropout: 0.3
          sttf:
            voxel_size: [0.4, 0.4, 4]
            downsample_rate: 4

    in_head: 256
    anchor_number: 2
    dir_args:
      dir_offset: 0.7853
      num_bins: 2
      anchor_yaw: [0, 90]

loss:
  core_method: "point_pillar_depth_loss"
  args:
    pos_cls_weight: 2.0
    cls:
      type: "SigmoidFocalLoss"
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: "WeightedSmoothL1Loss"
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: "WeightedSoftmaxClassificationLoss"
      weight: 0.2
      args:
        dir_offset: 0.7853
        num_bins: 2
        anchor_yaw: [0, 90]
    depth:
      weight: 1.0

optimizer:
  core_method: "Adam"
  lr: 0.0002
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: "multistep"
  gamma: 0.1
  step_size: [10, 25]

