name: v2v4real_point_pillar_stage1_pointpillar
root_dir: "dataset/v2v4real/train"
validate_dir: "dataset/v2v4real/validate"
test_dir: "dataset/v2v4real/test"

yaml_parser: "load_point_pillar_params"

# This hypes is used to export per-agent stage1 boxes (local-frame) for pose correction
# methods like FreeAlign / V2XReg++ via `opencood/tools/pose_graph_pre_calc.py`.
train_params:
  batch_size: &batch_size 1
  epoches: 1
  eval_freq: 1
  save_freq: 1
  max_cav: &max_cav 2

input_source: ['lidar']
label_type: 'lidar'
comm_range: 70

fusion:
  core_method: 'intermediate'
  dataset: 'v2v4real'
  args:
    proj_first: false

noise_setting:
  add_noise: false
  args:
    pos_mean: 0.0
    pos_std: 0.0
    rot_mean: 0.0
    rot_std: 0.0
    target: all

preprocess:
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 8]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  cav_lidar_range: &cav_lidar [-140.8, -38.4, -5.0, 140.8, 38.4, 3.0]

# Not used by stage1 export, but kept to satisfy yaml parser consistency.
data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]
  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]
  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

# Use UncertaintyVoxelPostprocessor because it provides `post_process_stage1`.
postprocess:
  core_method: 'UncertaintyVoxelPostprocessor'
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 4
    num: &anchor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    # Lower threshold for stage1 export: better recall for pose matching.
    score_threshold: 0.05
  order: 'hwl'
  max_num: 100
  nms_thresh: 0.15
  # Stage1 export speed knobs (used only by UncertaintyVoxelPostprocessor.post_process_stage1).
  stage1_nms_type: 'axis'     # rotated (slow, shapely) | axis (fast) | none
  stage1_nms_topk: 200        # pre-filter to top-K boxes before running NMS
  stage1_keep_topk: 80        # final cap on exported boxes per agent (keeps JSON size manageable)
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

model:
  core_method: point_pillar
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *anchor_num

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 2 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384

    dir_args: *dir_args

loss:
  core_method: point_pillar_depth_loss
  args:
    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args
    depth:
      weight: 0.0

optimizer:
  core_method: Adam
  lr: 0.001
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size: [15, 50]
