name: opv2v_point_pillar_lidar_pastat_noise1
root_dir: "dataset/OPV2V/train"
validate_dir: "dataset/OPV2V/validate"
test_dir: "dataset/OPV2V/test"

# Optional scenario filtering for reproducible subsets.
scenario_list:
  train: "opencood/splits/opv2v/default/train_scenarios.json"
  val: "opencood/splits/opv2v/default/val_scenarios.json"
  test: "opencood/splits/opv2v/default/test_scenarios.json"

yaml_parser: "load_point_pillar_params"

train_params:
  batch_size: &batch_size 2
  epoches: 60
  eval_freq: 2
  save_freq: 2
  max_cav: &max_cav 5

input_source: ['lidar']
label_type: 'lidar'
comm_range: 70

fusion:
  core_method: 'intermediate'
  dataset: 'opv2v'
  args:
    proj_first: false

# Synthetic GNSS-style Gaussian noise (m/deg) on poses.
noise_setting:
  add_noise: true
  args:
    pos_mean: 0.0
    pos_std: 1.0
    rot_mean: 0.0
    rot_std: 1.0
    target: all

preprocess:
  core_method: 'SpVoxelPreprocessor'
  args:
    voxel_size: &voxel_size [0.4, 0.4, 4]
    max_points_per_voxel: 32
    max_voxel_train: 32000
    max_voxel_test: 70000
  cav_lidar_range: &cav_lidar [-102.4, -102.4, -3, 102.4, 102.4, 1]

data_augment:
  - NAME: random_world_flip
    ALONG_AXIS_LIST: [ 'x' ]
  - NAME: random_world_rotation
    WORLD_ROT_ANGLE: [ -0.78539816, 0.78539816 ]
  - NAME: random_world_scaling
    WORLD_SCALE_RANGE: [ 0.95, 1.05 ]

postprocess:
  core_method: 'VoxelPostprocessor'
  gt_range: *cav_lidar
  anchor_args:
    cav_lidar_range: *cav_lidar
    l: 3.9
    w: 1.6
    h: 1.56
    r: &anchor_yaw [0, 90]
    feature_stride: 2
    num: &anchor_num 2
  target_args:
    pos_threshold: 0.6
    neg_threshold: 0.45
    score_threshold: 0.20
  order: 'hwl'
  max_num: 150
  nms_thresh: 0.15
  dir_args: &dir_args
    dir_offset: 0.7853
    num_bins: 2
    anchor_yaw: *anchor_yaw

model:
  core_method: point_pillar_baseline
  args:
    voxel_size: *voxel_size
    lidar_range: *cav_lidar
    anchor_number: *anchor_num

    pillar_vfe:
      use_norm: true
      with_distance: false
      use_absolute_xyz: true
      num_filters: [64]
    point_pillar_scatter:
      num_features: 64

    base_bev_backbone:
      layer_nums: [3, 5, 8]
      layer_strides: [2, 2, 2]
      num_filters: [64, 128, 256]
      upsample_strides: [1, 2, 4]
      num_upsample_filter: [128, 128, 128]

    shrink_header:
      kernal_size: [ 3 ]
      stride: [ 1 ]
      padding: [ 1 ]
      dim: [ 256 ]
      input_dim: 384

    fusion_method: pastat
    pastat:
      use_pose_confidence: true
      drop_confidence_channel: true
      confidence_embedding:
        embed_dim: 1
      fsa:
        hidden_channels: 128
        mlp_hidden: 128
        trans_limit: 8.0
        rot_limit_deg: 10.0
      transformer:
        encoder:
          num_blocks: 1
          depth: 3
          use_roi_mask: true
          use_RTE: false
          RTE_ratio: 0
          cav_att_config:
            dim: 256
            use_hetero: false
            use_RTE: false
            RTE_ratio: 0
            heads: 8
            dim_head: 32
            dropout: 0.3
          pwindow_att_config:
            dim: 256
            heads: [16, 8, 4]
            dim_head: [16, 32, 64]
            dropout: 0.3
            window_size: [4, 8, 16]
            relative_pos_embedding: true
            fusion_method: 'split_attn'
          feed_forward:
            mlp_dim: 256
            dropout: 0.3
          sttf:
            voxel_size: *voxel_size
            downsample_rate: 4

    dir_args: *dir_args

loss:
  core_method: point_pillar_depth_loss
  args:
    pos_cls_weight: 2.0
    cls:
      type: 'SigmoidFocalLoss'
      alpha: 0.25
      gamma: 2.0
      weight: 1.0
    reg:
      type: 'WeightedSmoothL1Loss'
      sigma: 3.0
      codewise: true
      weight: 2.0
    dir:
      type: 'WeightedSoftmaxClassificationLoss'
      weight: 0.2
      args: *dir_args
    depth:
      weight: 1.0

optimizer:
  core_method: Adam
  lr: 0.001
  args:
    eps: 1e-10
    weight_decay: 1e-4

lr_scheduler:
  core_method: multistep
  gamma: 0.1
  step_size: [15, 50]

